<?php
require_once __DIR__ . '/../includes/config.php';
require_once __DIR__ . '/../includes/functions.php';
requireRole('admin','stock');

$id = (int)($_GET['id'] ?? 0);
if (!$id) { header('Location: purchase_orders.php'); exit; }

$po = $pdo->prepare("SELECT po.*, s.name AS supplier_name, s.phone AS supplier_phone, s.address AS supplier_address, s.email AS supplier_email FROM purchase_orders po JOIN suppliers s ON s.id=po.supplier_id WHERE po.id=?");
$po->execute([$id]);
$po = $po->fetch();
if (!$po) { header('Location: purchase_orders.php'); exit; }

$items = $pdo->prepare("SELECT poi.*, p.barcode FROM purchase_order_items poi LEFT JOIN products p ON p.id=poi.product_id WHERE poi.po_id=? ORDER BY poi.id");
$items->execute([$id]);
$items = $items->fetchAll();

$storeName    = STORE_NAME;
$storeAddress = setting('store_address', '');
$storePhone   = setting('store_phone', '');
$rate         = EXCHANGE_RATE;

// ── WhatsApp share ────────────────────────────────────────────────────────────
if (isset($_GET['wa'])) {
    $phone = preg_replace('/[^0-9]/', '', $po['supplier_phone']);
    if (!$phone) { header('Location: purchase_orders.php?id='.$id); exit; }

    $lines   = [];
    $lines[] = "📋 *PURCHASE ORDER* — " . $po['po_number'];
    $lines[] = "From: *$storeName*";
    $lines[] = "To: *{$po['supplier_name']}*";
    if ($po['delivery_date']) $lines[] = "Delivery: " . date('d/m/Y', strtotime($po['delivery_date']));
    $lines[] = "";
    $lines[] = "*Items:*";
    $total = 0;
    foreach ($items as $idx => $item) {
        $n   = $idx + 1;
        $sub = $item['quantity'] * $item['estimated_price'];
        $total += $sub;
        $line = "$n. {$item['product_name']} — {$item['quantity']} {$item['unit']}";
        if ($item['estimated_price'] > 0) $line .= " @ \$" . number_format($item['estimated_price'],2) . " = \$" . number_format($sub,2);
        if ($item['note']) $line .= " ({$item['note']})";
        $lines[] = $line;
    }
    if ($total > 0) { $lines[] = ""; $lines[] = "💰 *Est. Total: \$" . number_format($total, 2) . "*"; }
    if ($po['note']) { $lines[] = ""; $lines[] = "📝 Note: " . $po['note']; }
    $lines[] = "";
    $lines[] = "_Generated by $storeName POS — " . date('d/m/Y H:i') . "_";

    $text = implode("\n", $lines);
    $url  = "https://wa.me/$phone?text=" . rawurlencode($text);
    header("Location: $url");
    exit;
}

$totalEst = array_sum(array_map(fn($i) => $i['quantity'] * $i['estimated_price'], $items));

$statusLabel = ucfirst($po['status']);
$statusBg    = ['draft'=>'#6c757d','sent'=>'#0d6efd','confirmed'=>'#0dcaf0','received'=>'#198754','cancelled'=>'#dc3545'][$po['status']] ?? '#6c757d';
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><?= htmlspecialchars($po['po_number']) ?> — <?= htmlspecialchars($storeName) ?></title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
<style>
* { box-sizing: border-box; }
body { background: #f3f4f6; font-family: Arial, sans-serif; }
.po-wrapper { max-width: 820px; margin: 20px auto; background: #fff; box-shadow: 0 4px 20px rgba(0,0,0,.12); border-radius: 10px; overflow: hidden; }
.po-header { background: linear-gradient(135deg,#1a3a1a,#2d5a2d); color: #fff; padding: 24px 32px; display: flex; justify-content: space-between; align-items: flex-start; }
.po-header .logo { height: 60px; object-fit: contain; border-radius: 6px; background: rgba(255,255,255,.15); padding: 4px; }
.po-body { padding: 28px 32px; }
.po-meta { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 24px; }
.meta-box { background: #f8f9fa; border-radius: 8px; padding: 14px 16px; }
.meta-box .label { font-size: 10px; text-transform: uppercase; letter-spacing: .5px; color: #6c757d; margin-bottom: 4px; }
.meta-box .value { font-size: 14px; font-weight: 600; color: #1f2937; }
.meta-box .sub   { font-size: 12px; color: #6b7280; margin-top: 2px; }
table.po-items { width: 100%; border-collapse: collapse; font-size: 13px; }
table.po-items th { background: #1a3a1a; color: #fff; padding: 9px 12px; text-align: left; }
table.po-items td { padding: 9px 12px; border-bottom: 1px solid #e5e7eb; }
table.po-items tr:last-child td { border-bottom: none; }
table.po-items tr:hover td { background: #f9fafb; }
.total-row { background: #f0fdf4 !important; font-weight: 700; }
.status-badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; color: #fff; background: <?= $statusBg ?>; }
.po-footer { border-top: 1px solid #e5e7eb; padding: 16px 32px; color: #9ca3af; font-size: 11px; text-align: center; }
.actions-bar { display: flex; gap: 10px; padding: 14px 32px; background: #f3f4f6; border-bottom: 1px solid #e5e7eb; flex-wrap: wrap; }
@media print {
    body { background: #fff; }
    .actions-bar { display: none !important; }
    .po-wrapper { box-shadow: none; margin: 0; border-radius: 0; }
}
</style>
</head>
<body>

<div class="po-wrapper">

<!-- Action bar (hidden on print) -->
<div class="actions-bar">
    <button onclick="window.print()" class="btn btn-sm btn-primary"><i class="bi bi-printer me-1"></i>Print PDF</button>
    <?php
    $phone = preg_replace('/[^0-9]/', '', $po['supplier_phone'] ?? '');
    if ($phone): ?>
    <button type="button" class="btn btn-sm btn-success" onclick="sendWhatsApp()"><i class="bi bi-whatsapp me-1"></i>Send via WhatsApp</button>
    <?php endif; ?>
    <a href="purchase_orders.php" class="btn btn-sm btn-outline-secondary ms-auto"><i class="bi bi-arrow-left me-1"></i>Back</a>
</div>

<!-- PO Header -->
<div class="po-header">
    <div>
        <?php if (file_exists($_SERVER['DOCUMENT_ROOT'].'/dahdouh/assets/img/logo.png')): ?>
        <img src="/dahdouh/assets/img/logo.png" class="logo mb-2" alt="logo">
        <br>
        <?php endif; ?>
        <div style="font-size:18px;font-weight:700;letter-spacing:.3px"><?= htmlspecialchars($storeName) ?></div>
        <?php if ($storeAddress): ?><div style="font-size:12px;opacity:.8"><?= htmlspecialchars($storeAddress) ?></div><?php endif; ?>
        <?php if ($storePhone): ?><div style="font-size:12px;opacity:.8"><?= htmlspecialchars($storePhone) ?></div><?php endif; ?>
    </div>
    <div style="text-align:right">
        <div style="font-size:11px;opacity:.7;text-transform:uppercase;letter-spacing:.5px">Purchase Order</div>
        <div style="font-size:22px;font-weight:800;letter-spacing:.5px"><?= htmlspecialchars($po['po_number']) ?></div>
        <div style="margin-top:8px"><span class="status-badge"><?= $statusLabel ?></span></div>
        <div style="font-size:12px;opacity:.7;margin-top:6px">Date: <?= date('d/m/Y', strtotime($po['created_at'])) ?></div>
        <?php if ($po['delivery_date']): ?>
        <div style="font-size:12px;opacity:.7">Delivery: <?= date('d/m/Y', strtotime($po['delivery_date'])) ?></div>
        <?php endif; ?>
    </div>
</div>

<!-- Body -->
<div class="po-body">

<!-- Meta boxes -->
<div class="po-meta">
    <div class="meta-box">
        <div class="label">From (Buyer)</div>
        <div class="value"><?= htmlspecialchars($storeName) ?></div>
        <?php if ($storeAddress): ?><div class="sub"><?= htmlspecialchars($storeAddress) ?></div><?php endif; ?>
        <?php if ($storePhone): ?><div class="sub"><?= htmlspecialchars($storePhone) ?></div><?php endif; ?>
    </div>
    <div class="meta-box">
        <div class="label">To (Supplier)</div>
        <div class="value"><?= htmlspecialchars($po['supplier_name']) ?></div>
        <?php if ($po['supplier_address']): ?><div class="sub"><?= htmlspecialchars($po['supplier_address']) ?></div><?php endif; ?>
        <?php if ($po['supplier_phone']): ?><div class="sub">📞 <?= htmlspecialchars($po['supplier_phone']) ?></div><?php endif; ?>
        <?php if ($po['supplier_email']): ?><div class="sub">✉ <?= htmlspecialchars($po['supplier_email']) ?></div><?php endif; ?>
    </div>
</div>

<!-- Note -->
<?php if ($po['note']): ?>
<div style="background:#fffbeb;border:1px solid #fcd34d;border-radius:6px;padding:10px 14px;margin-bottom:20px;font-size:13px;">
    <strong>Note:</strong> <?= htmlspecialchars($po['note']) ?>
</div>
<?php endif; ?>

<!-- Items table -->
<table class="po-items">
    <thead>
        <tr>
            <th>#</th>
            <th>Product / Description</th>
            <th>Quantity</th>
            <th>Unit</th>
            <th>Est. Unit Price</th>
            <th>Est. Total</th>
            <th>Note</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($items as $idx => $item):
        $sub = $item['quantity'] * $item['estimated_price'];
    ?>
    <tr>
        <td><?= $idx + 1 ?></td>
        <td>
            <strong><?= htmlspecialchars($item['product_name']) ?></strong>
            <?php if ($item['barcode']): ?><br><span style="font-size:10px;color:#9ca3af"><?= htmlspecialchars($item['barcode']) ?></span><?php endif; ?>
        </td>
        <td><?= (float)$item['quantity'] ?></td>
        <td><?= htmlspecialchars($item['unit']) ?></td>
        <td><?= $item['estimated_price'] > 0 ? '$' . number_format($item['estimated_price'],2) : '<span style="color:#9ca3af">—</span>' ?></td>
        <td><?= $sub > 0 ? '$' . number_format($sub, 2) : '<span style="color:#9ca3af">—</span>' ?></td>
        <td style="color:#6b7280"><?= htmlspecialchars($item['note'] ?? '') ?></td>
    </tr>
    <?php endforeach; ?>
    <?php if ($totalEst > 0): ?>
    <tr class="total-row">
        <td colspan="5" style="text-align:right;padding-right:16px">ESTIMATED TOTAL:</td>
        <td style="font-size:15px">$<?= number_format($totalEst, 2) ?></td>
        <td></td>
    </tr>
    <?php endif; ?>
    </tbody>
</table>

<!-- Signatures -->
<div style="display:grid;grid-template-columns:1fr 1fr;gap:40px;margin-top:48px">
    <div>
        <div style="border-top:1px solid #374151;padding-top:8px;font-size:12px;text-align:center;color:#6b7280">Authorized by (<?= htmlspecialchars($storeName) ?>)</div>
    </div>
    <div>
        <div style="border-top:1px solid #374151;padding-top:8px;font-size:12px;text-align:center;color:#6b7280">Received by (<?= htmlspecialchars($po['supplier_name']) ?>)</div>
    </div>
</div>

</div><!-- body -->

<div class="po-footer">
    Generated by <?= htmlspecialchars($storeName) ?> POS on <?= date('d/m/Y H:i') ?> ·
    <?= htmlspecialchars($po['po_number']) ?> · <?= count($items) ?> item(s)
</div>

</div>
<script>
function sendWhatsApp() {
    window.open('/dahdouh/pages/po_view.php?id=<?= $id ?>&autoprint=1', '_blank');
    setTimeout(function() {
        var msg = encodeURIComponent(
            'Please find attached Purchase Order <?= addslashes($po['po_number']) ?> from <?= addslashes($storeName) ?>.\nKindly confirm receipt.'
        );
        window.open('https://wa.me/<?= $phone ?>?text=' + msg, '_blank');
    }, 1500);
}
<?php if (isset($_GET['autoprint'])): ?>
window.addEventListener('load', function() { window.print(); });
<?php endif; ?>
</script>
</body>
</html>
